version: '2.4'
services:
  nwnxee-server:
    container_name: nwnxee-server
    image: nwnxee/unified:latest-full
    env_file: ./config/nwserver.env
    stdin_open: true
    tty: true
    links:
      - "db:db"
      - "redis:redis"
      - "grafana:grafana"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ~/GAME_RES/:/nwn/home
    restart: always
    ports:
      - "5121:5121/udp"
  db:
    container_name: db
    image: mysql/mysql-server:5.7
    env_file: ./config/db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
  redis:
    container_name: redis
    image: healthcheck/redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis:/data
    restart: unless-stopped
  grafana:
    image: philhawthorne/docker-influxdb-grafana:edge
    container_name: grafana
    volumes:
      - "./metrics/influxdb:/var/lib/influxdb"
      - "./metrics/grafana:/var/lib/grafana"
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"

